version: '3.8'
services:
  backend:
    build: ./backend
    container_name: skate_backend
    command: 'python manage.py runserver 0.0.0.0:8000'
    expose:
      - '8000'
    environment:
      - 'SECRET_KEY=${SECRET_KEY}'
      - DEBUG=True
      - 'DATABASE_URL=${DATABASE_URL}' 
  
  frontend:
    build: ./frontend
    expose:
      - '5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

